### ISSUE TITLE
Trailing whitespaces

### ISSUE THREAD

**Issue by dmitri-zganiaiko** [DannyBen/kojo#43]
Kojo produces trailing whitespaces. Obviously, they can be removed with something like `sed` after running `kojo`, but it would be preferred if `kojo` would not add them at all.

An example.

Input files:

```bash
$ ls in
child1.yml child2.yml parent.yml root.yml
$ cat in/root.yml
- name: "root"
  steps:
    @import parent
$ cat in/parent.yml
- name: "parent"
  steps:
    @import child1

    @import child2

$ cat in/child1.yml
- name: "child1"
$ cat in/child2.yml
- name: "child2"
```

No trailing whitespace in `parent.yml`:

```bash
$ cat in/parent.yml| sed 's/ /./g'
-.name:."parent"
..steps:
....@import.child1

....@import.child2
```

Generation:

```bash
$ kojo dir in --save out
Saved out/child1.yml
Saved out/child2.yml
    @import child1
    @import child2
Saved out/parent.yml
    @import parent
    @import child1
    @import child2
Saved out/root.yml
```

`root.yml` contains a line with trailing spaces between `child1` and `child2`.

```
$ cat out/root.yml | sed -E 's/ /./g'
-.name:."root"
..steps:
....-.name:."parent"
......steps:
........-.name:."child1"
....
........-.name:."child2"
```

An expected result is without spaces:

```
$ cat out/root.yml | sed -E 's/ /./g'
-.name:."root"
..steps:
....-.name:."parent"
......steps:
........-.name:."child1"

........-.name:."child2"
```

Could you please add automatic trimming of the lines that are whitespace-only?

**Comment by DannyBen** [comment]
Why do you care about these spaces in an empty line? This forms a perfectly valid YAML still.

The problem happens since the `@import 'parent'` is indented (and rightfully so). Kojo prepends every line in that import with the same amount of spaces as the `@import` directive itself.

Note that kojo is not YAML specific, and while I agree it is nicer to have a cleanly generated YAML, there might be some other use cases where the indentation needs to be preserved even on empty lines.

Do you have a specific reason for wanting to remove them?

**Comment by DannyBen** [comment]
I have implemented a version that eliminates these lines in #44, in case you wish to test that it covers your use case.

**Comment by dmitri-zganiaiko** [comment]
> Why do you care about these spaces in an empty line?
> Do you have a specific reason for wanting to remove them?

Mainly, from readability and aesthetic point view:
- the diff looks better without trailing whitespaces
- there may be "redundant diffs" when those whitespaces are either removed or added along the "normal" changes - it clutters the diff

> This forms a perfectly valid YAML still.

And you're absolutely right, it is still a valid YAML :)

> Note that kojo is not YAML specific, and while I agree it is nicer to have a cleanly generated YAML, there might be some other use cases where the indentation needs to be preserved even on empty lines.

Hm, could you please give some examples when the line that only contains trailing whitespaces matters and should not be trimmed?

**Comment by DannyBen** [comment]
> Hm, could you please give some examples when the line that only contains trailing whitespaces matters and should not be trimmed?

The reason I could not find any, is the reason I implemented the change :)
I was thinking about some niche HEREDOC cases perhaps, but I agree that it is unlikely that anyone will complain about it.

**Comment by dmitri-zganiaiko** [comment]
> I have implemented a version that eliminates these lines in #44, in case you wish to test that it covers your use case.

Yes, it works, thank you.

**Comment by DannyBen** [comment]
Ok, I will merge and release in the next few days.

**Comment by garethsb** [comment]
My current use case is also building YAML from templates with some indented `@` imports, and I also prefer the new result since #44, thanks.

I can think of at least one possible use case where trailing whitespace is important: GitHub Flavored Markdown [Hard line breaks](https://github.github.com/gfm/#hard-line-breaks).

**Comment by DannyBen** [comment]
> and I also prefer the new result since https://github.com/DannyBen/kojo/pull/44

Excellent. Thanks for the additional input.
